<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="https://maven.apache.org/POM/4.0.0"
         xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.joaopfsuarez</groupId>
    <artifactId>biscuitclicker</artifactId>
    <version>1.0.4</version>

    <name>Biscuit Clicker</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <maven.compiler.release>21</maven.compiler.release>
        <javafx.version>21</javafx.version>
    </properties>

    <dependencies>

        <!-- Provides JavaFX UI controls such as buttons, labels and text fields -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>

        <!-- Provides support for loading and using FXML files -->
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Compiles the project using Java 21 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>

                <configuration>
                    <release>
                        ${maven.compiler.release}
                    </release>
                </configuration>
            </plugin>

            <!-- Allows the JavaFX application to be run with Maven -->
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>

                <configuration>
                    <mainClass>
                        com.joaopfsuarez.biscuitclicker/com.joaopfsuarez.biscuitclicker.Main
                    </mainClass>
                </configuration>
            </plugin>

            <!-- Configures the main class of the generated JAR file -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>

                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>
                                com.joaopfsuarez.biscuitclicker.Main
                            </mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <!-- Copies project dependencies to the target/libs directory -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.7.1</version>

                <executions>
                    <execution>
                        <id>copy-deps</id>
                        <phase>package</phase>

                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>

                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/libs
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
